"""Inference code for the sepsis early-warning prototype. Generated by Sepsis_ML_Master.ipynb (section 19). Do not edit by hand."""
import json, math
from collections import deque
from pathlib import Path
import numpy as np
import torch
import torch.nn as nn

MAX_ROWS = 336                      # longest stay in the training data
TREND_STEP = {"HR": 10, "O2Sat": 2, "Temp": 0.5, "SBP": 15, "MAP": 10, "DBP": 10, "Resp": 4}
UNITS = {"HR": "bpm", "O2Sat": "%", "Temp": "C", "SBP": "mmHg", "MAP": "mmHg", "DBP": "mmHg", "Resp": "breaths/min"}
DISCLAIMER = ("Research prototype trained on retrospective PhysioNet/CinC 2019 data. "
              "Not a diagnostic tool and not clinically validated; do not use for patient care decisions.")
HERE = Path(__file__).resolve().parent if "__file__" in globals() else Path(".")


def make_windows(F, rows, starts, W):
    """NumPy windows [len(rows), W, k]; NaN where the window runs before the stay begins. Also returns the validity mask."""
    off = np.arange(-W + 1, 1)
    idx = rows[:, None] + off[None, :]
    ok = idx >= starts[rows][:, None]
    out = F[np.clip(idx, 0, len(F) - 1)].copy()
    out[~ok] = np.nan
    return out, ok

FEAT_STATS = ["cur", "mean", "std", "min", "max", "slope", "delta", "obsfrac"]
def window_features(Vs, I, rows, starts, W):
    """Vs: scaled filled vitals [N,7]; I: measured flags [N,7]. Uses only hours <= each row."""
    win, ok = make_windows(Vs, rows, starts, W)
    iw, _ = make_windows(I, rows, starts, W)
    cur = win[:, -1]; mean = np.nanmean(win, 1); std = np.nanstd(win, 1); mn = np.nanmin(win, 1); mx = np.nanmax(win, 1)
    nv = ok.sum(1)[:, None]
    first = np.take_along_axis(win, np.argmax(ok, 1)[:, None, None].repeat(win.shape[2], 2), 1)[:, 0]
    slope = (cur - first) / np.maximum(nv - 1, 1)
    prev = np.where(nv > 1, win[:, -2], cur)
    delta = cur - np.nan_to_num(prev, nan=0.0)
    frac = np.nansum(iw, 1) / nv
    return np.concatenate([cur, mean, std, mn, mx, slope, delta, frac], 1).astype(np.float32)

class SeqClassifier(nn.Module):
    def __init__(self, n_in, hidden=64, layers=2, dropout=0.2, cell="lstm"):
        super().__init__()
        rnn = nn.LSTM if cell == "lstm" else nn.GRU
        self.rnn = rnn(n_in, hidden, num_layers=layers, batch_first=True, dropout=dropout if layers > 1 else 0.0)
        self.drop = nn.Dropout(dropout)
        self.fc = nn.Linear(hidden, 1)
    def forward(self, x):
        h, _ = self.rnn(x)
        return self.fc(self.drop(h[:, -1])).squeeze(-1)          # logit; sigmoid is applied outside

class Encoder(nn.Module):
    def __init__(self, n_in, hidden=64, latent=32, layers=1, cell="lstm"):
        super().__init__()
        rnn = nn.LSTM if cell == "lstm" else nn.GRU
        self.rnn = rnn(n_in, hidden, num_layers=layers, batch_first=True)
        self.to_z = nn.Linear(hidden, latent)
    def forward(self, x):
        h, _ = self.rnn(x)
        return self.to_z(h[:, -1])

class Autoencoder(nn.Module):
    def __init__(self, n_in, n_out, W, hidden=64, latent=32):
        super().__init__()
        self.W = W
        self.enc = Encoder(n_in, hidden, latent)
        self.dec = nn.LSTM(latent, hidden, batch_first=True)
        self.out = nn.Linear(hidden, n_out)
    def forward(self, x):
        z = self.enc(x)
        h, _ = self.dec(z[:, None, :].repeat(1, self.W, 1))
        return self.out(h), z

class SepsisHead(nn.Module):
    def __init__(self, latent, hidden=64, dropout=0.2):
        super().__init__()
        self.net = nn.Sequential(nn.Linear(latent, hidden), nn.ReLU(), nn.Dropout(dropout), nn.Linear(hidden, 1))
    def forward(self, z):
        return self.net(z).squeeze(-1)

class SepsisPredictor:
    """Loads the trained model + preprocessing artifacts and scores hourly vital-sign histories."""
    def __init__(self, models_dir=None, artifacts_dir=None):
        models_dir = Path(models_dir or HERE / "models"); artifacts_dir = Path(artifacts_dir or HERE / "artifacts")
        cfg = json.load(open(artifacts_dir / "config.json")); cal = json.load(open(artifacts_dir / "calibration.json"))
        sc = json.load(open(artifacts_dir / "scaler.json")); md = json.load(open(artifacts_dir / "medians.json"))
        self.cfg, self.W, self.vitals, self.ranges = cfg, cfg["sequence_length"], cfg["vitals"], cfg["valid_ranges"]
        self.base = cal["base_rate"]; self.pa, self.pb = cal["platt_a"], cal["platt_b"]
        self.t_high, self.t_elev = cal["high_raw_threshold"], cal["elevated_raw_threshold"]
        self.cal = cal
        self.mean = np.array(sc["mean"], dtype=np.float32); self.std = np.array(sc["std"], dtype=np.float32)
        self.med = np.array(md["median"], dtype=np.float32)
        ck = torch.load(models_dir / "final_sepsis_model.pt", map_location="cpu")
        self.enc = Encoder(ck["n_in"], ck["hidden"], ck["latent"]); self.enc.load_state_dict(ck["enc"])
        self.head = SepsisHead(ck["latent"]); self.head.load_state_dict(ck["head"])
        self.enc.eval(); self.head.eval()
        self.off = torch.arange(-self.W + 1, 1)

    # 1. validate input ------------------------------------------------------------------------------------
    def _parse(self, payload):
        hist = payload.get("history", payload.get("vitals")) if isinstance(payload, dict) else payload
        if not isinstance(hist, list) or not hist:
            raise ValueError("input must contain a non-empty 'history' list of hourly records")
        rows, ignored = {}, set()
        for i, rec in enumerate(hist):
            if not isinstance(rec, dict) or "hour" not in rec:
                raise ValueError("history[%d] must be an object with an 'hour' field" % i)
            h = rec["hour"]
            if isinstance(h, bool) or not isinstance(h, (int, float)) or not math.isfinite(h) or h != int(h):
                raise ValueError("history[%d].hour must be a whole number" % i)
            h = int(h)
            if h in rows:
                raise ValueError("duplicate hour %d" % h)
            vals = []
            for v in self.vitals:
                x = rec.get(v)
                if x is None:
                    vals.append(np.nan); continue
                if isinstance(x, bool) or not isinstance(x, (int, float)):
                    raise ValueError("history[%d].%s must be a number or null" % (i, v))
                if not math.isfinite(x):
                    raise ValueError("history[%d].%s is not a finite number" % (i, v))
                vals.append(float(x))
            rows[h] = vals
            ignored |= set(rec) - set(self.vitals) - {"hour"}
        hours = sorted(rows); warn = []
        full = np.arange(hours[0], hours[-1] + 1)
        V = np.full((len(full), len(self.vitals)), np.nan, dtype=np.float32)
        for h in hours:
            V[h - full[0]] = rows[h]
        if len(full) - len(hours):
            warn.append("%d hour(s) missing from the hourly series were treated as unmeasured." % (len(full) - len(hours)))
        if len(full) > MAX_ROWS:
            V, full = V[-MAX_ROWS:], full[-MAX_ROWS:]
            warn.append("History longer than %d hours; only the most recent %d hours were used." % (MAX_ROWS, MAX_ROWS))
        return full, V, warn, sorted(ignored), len(hours)

    # 2-4. clean, fill from the past only, indicators, scale ------------------------------------------------
    def _features(self, V):
        V = V.copy(); bad = []
        for j, v in enumerate(self.vitals):
            lo, hi = self.ranges[v]
            m = (V[:, j] < lo) | (V[:, j] > hi)
            if m.any():
                bad.append("%s x%d" % (v, int(m.sum()))); V[m, j] = np.nan
        obs = ~np.isnan(V)
        filled = V.copy()
        for j in range(V.shape[1]):
            last = np.nan
            for t in range(len(filled)):                    # looks backwards in time only
                if np.isnan(filled[t, j]): filled[t, j] = last
                else: last = filled[t, j]
        lead = np.isnan(filled)
        filled[lead] = np.broadcast_to(self.med, filled.shape)[lead]
        F = np.concatenate([((filled - self.mean) / self.std).astype(np.float32), obs.astype(np.float32)], 1)
        return V, obs, F, bad

    # 5-6. latest-6-hour windows, zero-padded at the start of a stay -----------------------------------------
    def _windows(self, F):
        Ft = torch.from_numpy(F); idx = torch.arange(len(F))[:, None] + self.off[None, :]
        ok = idx >= 0
        x = Ft[idx.clamp(min=0)] * ok[..., None]
        return torch.cat([x, ok[..., None].float()], 2)

    # 7-8. model, calibration, alert level ---------------------------------------------------------------------
    def _raw(self, x):
        with torch.no_grad():
            return torch.sigmoid(self.head(self.enc(x))).numpy()
    def _calibrate(self, p):
        p = np.clip(np.asarray(p, dtype=np.float64), 1e-6, 1 - 1e-6)
        return 1 / (1 + np.exp(-(self.pa * np.log(p / (1 - p)) + self.pb)))
    def _tier(self, raw):
        return "HIGH" if raw >= self.t_high else ("ELEVATED" if raw >= self.t_elev else "LOW")

    def predict_series(self, history):
        """Score every hour of a history (each hour uses only itself and earlier hours)."""
        hours, V, warn, ignored, n_given = self._parse(history)
        _, _, F, _ = self._features(V)
        raw = self._raw(self._windows(F)); cal = self._calibrate(raw)
        return [dict(hour=int(h), model_score=float(r), sepsis_probability=float(c), risk_level=self._tier(r)) for h, r, c in zip(hours, raw, cal)]

    def predict(self, history):
        """Score the latest hour. Returns the probability, level, warnings, trends and sensitivity analysis."""
        hours, V, warn, ignored, n_given = self._parse(history)
        Vc, obs, F, bad = self._features(V)
        X = self._windows(F); raw = float(self._raw(X)[-1]); prob = float(self._calibrate(raw))
        W = self.W
        if bad: warn.append("Values outside the plausible range were treated as missing: " + ", ".join(bad) + ".")
        if len(hours) < W: warn.append("Only %d hour(s) of history; the %d-hour window is padded, so the score is less reliable." % (len(hours), W))
        if not obs[-1].any(): warn.append("No vitals recorded at the latest hour; the last known values are carried forward.")
        for j, v in enumerate(self.vitals):
            if not obs[:, j].any(): warn.append("%s was never measured in the supplied history; the training median was used." % v)
        if ignored: warn.append("Ignored fields (this model uses only the 7 vitals): " + ", ".join(ignored) + ".")
        recent = obs[-W:]
        sparse = [v for j, v in enumerate(self.vitals) if obs[:, j].any() and recent[:, j].sum() <= 1]
        if sparse and len(hours) >= W: warn.append("Measured at most once in the last %d hours: %s." % (W, ", ".join(sparse)))
        trends = {}
        for j, v in enumerate(self.vitals):
            w = Vc[-W:, j]; ok = ~np.isnan(w); seen = np.flatnonzero(obs[:, j])
            ago = int(len(hours) - 1 - seen[-1]) if len(seen) else None
            if ok.sum() >= 2:
                ch = float(w[ok][-1] - w[ok][0])
                d = "up" if ch >= TREND_STEP[v] else ("down" if ch <= -TREND_STEP[v] else "stable")
                trends[v] = dict(direction=d, change=round(ch, 1), unit=UNITS[v], last_value=round(float(w[ok][-1]), 1), hours_since_measured=ago)
            else:
                trends[v] = dict(direction="insufficient data", change=None, unit=UNITS[v], last_value=round(float(w[ok][-1]), 1) if ok.any() else None, hours_since_measured=ago)
        # sensitivity: set one vital to its training median (and mark it unmeasured) in the latest window and see how the probability moves
        xw = X[-1:].clone(); valid = xw[..., -1:]; nv = len(self.vitals)
        smed = torch.from_numpy(((self.med - self.mean) / self.std).astype(np.float32))
        eff = []
        for j, v in enumerate(self.vitals):
            x2 = xw.clone(); x2[..., j:j + 1] = valid * smed[j]; x2[..., nv + j:nv + j + 1] = 0
            eff.append((v, prob - float(self._calibrate(self._raw(x2)[0]))))
        eff.sort(key=lambda a: -abs(a[1]))
        sens = [dict(feature=v, effect_on_probability_pct_points=round(100 * d, 2), direction="raises" if d > 0 else "lowers") for v, d in eff]
        hist_hours = int(min(len(hours), W))
        return dict(as_of_hour=int(hours[-1]), sepsis_probability=round(prob, 4), risk_level=self._tier(raw), model_score=round(raw, 4),
                    baseline_rate=round(self.base, 4), times_baseline=round(prob / self.base, 2), history_hours=hist_hours,
                    hours_with_data=int(n_given), recent_trends=trends, sensitivity=sens, top_associated_features=sens[:3],
                    warnings=warn, ignored_fields=ignored,
                    note="Sensitivity comes from setting one vital at a time to its typical value. It describes the model's behaviour, not causes.",
                    disclaimer=DISCLAIMER)

class StreamPredictor:
    """Rolling monitor. Feed one hourly measurement at a time; keeps the model's 6-hour window in a deque(maxlen=6).
    Alongside it keeps the last measured value of each vital so forward-filling matches the offline pipeline exactly."""
    def __init__(self, model):
        self.m = model; self.win = deque(maxlen=model.W); self.raw_win = deque(maxlen=model.W)
        self.last = np.full(len(model.vitals), np.nan, dtype=np.float32)
        self.hour = None; self.risk_history = []; self.n_seen = 0; self.warn_bad = []

    def _step(self, vals):
        m = self.m; v = np.array(vals, dtype=np.float32).copy(); self.warn_bad = []
        for j, name in enumerate(m.vitals):
            lo, hi = m.ranges[name]
            if not np.isnan(v[j]) and (v[j] < lo or v[j] > hi):
                self.warn_bad.append(name); v[j] = np.nan
        obs = ~np.isnan(v)
        self.last[obs] = v[obs]
        filled = np.where(np.isnan(self.last), m.med, self.last)
        self.win.append(np.concatenate([((filled - m.mean) / m.std).astype(np.float32), obs.astype(np.float32)]))
        self.raw_win.append(v); self.n_seen += 1

    def push(self, vitals, hour=None):
        m = self.m
        vals = []
        for name in m.vitals:
            x = vitals.get(name)
            if x is None or (isinstance(x, float) and math.isnan(x)): vals.append(np.nan)
            elif isinstance(x, bool) or not isinstance(x, (int, float)) or not math.isfinite(x): raise ValueError("%s must be a finite number or null" % name)
            else: vals.append(float(x))
        nxt = 1 if self.hour is None else self.hour + 1
        hour = nxt if hour is None else int(hour)
        if self.hour is not None and hour <= self.hour: raise ValueError("hour must increase (got %d after %d)" % (hour, self.hour))
        for _ in range(max(0, hour - nxt)): self._step([np.nan] * len(m.vitals))     # skipped hours count as unmeasured
        self._step(vals); self.hour = hour
        rows = list(self.win); pad = m.W - len(rows)
        arr = np.zeros((m.W, len(m.vitals) * 2 + 1), dtype=np.float32)
        for k, r in enumerate(rows): arr[pad + k, :-1] = r; arr[pad + k, -1] = 1.0
        raw = float(m._raw(torch.from_numpy(arr)[None])[0]); prob = float(m._calibrate(raw))
        warns = []
        if pad > 0: warns.append("Only %d of %d hours of history so far; the score is less reliable." % (len(rows), m.W))
        if self.warn_bad: warns.append("Implausible value(s) treated as missing: " + ", ".join(self.warn_bad) + ".")
        if not any(not np.isnan(x) for x in vals): warns.append("No vitals recorded this hour; last known values carried forward.")
        rec = dict(hour=hour, sepsis_probability=prob, model_score=raw, risk_level=m._tier(raw), history_hours=len(rows), warning="; ".join(warns) or None,
                   vitals={n: (None if np.isnan(x) else float(x)) for n, x in zip(m.vitals, vals)})
        self.risk_history.append(rec)
        return rec

def load_model(models_dir=None, artifacts_dir=None):
    """Load the trained network, scaler, training medians, calibration and configuration."""
    return SepsisPredictor(models_dir, artifacts_dir)

_DEFAULT = None
def predict_sepsis(history, model=None):
    """history: list of hourly records {"hour", "HR", "O2Sat", "Temp", "SBP", "MAP", "DBP", "Resp"} (values may be null/missing).
    Pass the full history so far (up to 336 hours); the model uses the latest 6, older hours only feed the forward-fill."""
    global _DEFAULT
    if model is None:
        if _DEFAULT is None: _DEFAULT = load_model()
        model = _DEFAULT
    r = model.predict(history if isinstance(history, dict) else {"history": history})
    return dict(sepsis_probability=r["sepsis_probability"], risk_level=r["risk_level"], history_hours=r["history_hours"],
                warning=" ".join(r["warnings"]) or None)

class ModelHub:
    """Runs every model in artifacts/model_registry.json on the same preprocessed history."""
    def __init__(self, models_dir=None, artifacts_dir=None):
        self.models_dir = Path(models_dir or HERE / "models"); self.art = Path(artifacts_dir or HERE / "artifacts")
        self.base = SepsisPredictor(self.models_dir, self.art)          # shared validation, cleaning, fill, scaling, windows
        self.reg = json.load(open(self.art / "model_registry.json"))
        self.primary = self.reg["primary"]; self.info = {m["key"]: m for m in self.reg["models"]}; self.nets = {}
        for m in self.reg["models"]:
            f = HERE / m["file"] if (HERE / m["file"]).exists() else self.models_dir / Path(m["file"]).name
            k = m["kind"]
            if k == "tabular_lr":
                import joblib; self.nets[m["key"]] = joblib.load(f)
            elif k == "tabular_xgb":
                import xgboost as xgb; net = xgb.XGBClassifier(); net.load_model(str(f)); self.nets[m["key"]] = net
            elif k in ("sequence_lstm", "sequence_gru"):
                net = SeqClassifier(self.base.enc.rnn.input_size, 64, 2, 0.2, "lstm" if k.endswith("lstm") else "gru")
                net.load_state_dict(torch.load(f, map_location="cpu")); self.nets[m["key"]] = net.eval()
            elif m["key"] == self.primary:
                self.nets[m["key"]] = None                               # the base predictor already holds it
            else:
                ck = torch.load(f, map_location="cpu"); n_in = self.base.enc.rnn.input_size
                enc = Encoder(n_in, 64, 32); enc.load_state_dict(ck["enc"]); head = SepsisHead(32); head.load_state_dict(ck["head"])
                self.nets[m["key"]] = (enc.eval(), head.eval())

    def raw_scores(self, F):
        """F: [hours, 14] scaled values + flags. Returns {key: raw score for every hour}."""
        n = len(F); W = self.base.W; X = None; T = None; out = {}
        for key, net in self.nets.items():
            k = self.info[key]["kind"]
            if k.startswith("tabular"):
                if T is None:
                    T = window_features(F[:, :7], F[:, 7:14], np.arange(n), np.zeros(n, dtype=np.int64), W)
                out[key] = net.predict_proba(T)[:, 1]
            else:
                if X is None: X = self.base._windows(F)
                with torch.no_grad():
                    if key == self.primary: out[key] = self.base._raw(X)
                    elif isinstance(net, tuple): out[key] = torch.sigmoid(net[1](net[0](X))).numpy()
                    else: out[key] = torch.sigmoid(net(X)).numpy()
        return out

    def _cal(self, key, p):
        m = self.info[key]; p = np.clip(np.asarray(p, dtype=np.float64), 1e-6, 1 - 1e-6)
        return 1 / (1 + np.exp(-(m["platt_a"] * np.log(p / (1 - p)) + m["platt_b"])))

    def _level(self, key, raw):
        m = self.info[key]
        return "HIGH" if raw >= m["high_raw_threshold"] else ("ELEVATED" if raw >= m["elevated_raw_threshold"] else "LOW")

    def predict_all(self, payload):
        hours, V, warn, ignored, n_given = self.base._parse(payload)
        Vc, obs, F, bad = self.base._features(V)
        raw = self.raw_scores(F)
        if bad: warn.append("Values outside the plausible range were treated as missing: " + ", ".join(bad) + ".")
        if len(hours) < self.base.W: warn.append("Only %d hour(s) of history; the %d-hour window is padded, so the score is less reliable." % (len(hours), self.base.W))
        if not obs[-1].any(): warn.append("No vitals recorded at the latest hour; the last known values are carried forward.")
        for j, v in enumerate(self.base.vitals):
            if not obs[:, j].any(): warn.append("%s was never measured in the supplied history; the training median was used." % v)
        res = {}
        for key, r in raw.items():
            r = float(r[-1])
            res[key] = dict(name=self.info[key]["name"], kind=self.info[key]["kind"], model_score=round(r, 4),
                            sepsis_probability=round(float(self._cal(key, r)), 4), risk_level=self._level(key, r))
        return dict(primary=self.primary, as_of_hour=int(hours[-1]), history_hours=int(min(len(hours), self.base.W)), models=res,
                    warnings=warn, ignored_fields=ignored, disclaimer=DISCLAIMER)

    def comparison(self):
        f = HERE / "results" / "model_comparison.csv"
        if not f.exists(): return []
        import csv
        return list(csv.DictReader(open(f)))
