/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PortalIndexRouteImport } from './routes/_portal/index'
import { Route as PortalPrescriptionRouteImport } from './routes/_portal/prescription'
import { Route as PortalSharingRouteImport } from './routes/_portal/sharing'
import { Route as PortalVitalsRouteImport } from './routes/_portal/vitals'
import { Route as PortalXrayRouteImport } from './routes/_portal/xray'

const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPrescriptionRoute = PortalPrescriptionRouteImport.update({
  id: '/prescription',
  path: '/prescription',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSharingRoute = PortalSharingRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => PortalRoute,
} as any)
const PortalVitalsRoute = PortalVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => PortalRoute,
} as any)
const PortalXrayRoute = PortalXrayRouteImport.update({
  id: '/xray',
  path: '/xray',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PortalIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/prescription': typeof PortalPrescriptionRoute
  '/sharing': typeof PortalSharingRoute
  '/vitals': typeof PortalVitalsRoute
  '/xray': typeof PortalXrayRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/prescription': typeof PortalPrescriptionRoute
  '/sharing': typeof PortalSharingRoute
  '/vitals': typeof PortalVitalsRoute
  '/xray': typeof PortalXrayRoute
  '/': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_portal': typeof PortalRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_portal/prescription': typeof PortalPrescriptionRoute
  '/_portal/sharing': typeof PortalSharingRoute
  '/_portal/vitals': typeof PortalVitalsRoute
  '/_portal/xray': typeof PortalXrayRoute
  '/_portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/prescription'
    | '/sharing'
    | '/vitals'
    | '/xray'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/prescription'
    | '/sharing'
    | '/vitals'
    | '/xray'
    | '/'
  id:
    | '__root__'
    | '/_portal'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_portal/prescription'
    | '/_portal/sharing'
    | '/_portal/vitals'
    | '/_portal/xray'
    | '/_portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PortalRoute: typeof PortalRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/': {
      id: '/_portal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/prescription': {
      id: '/_portal/prescription'
      path: '/prescription'
      fullPath: '/prescription'
      preLoaderRoute: typeof PortalPrescriptionRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/sharing': {
      id: '/_portal/sharing'
      path: '/sharing'
      fullPath: '/sharing'
      preLoaderRoute: typeof PortalSharingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/vitals': {
      id: '/_portal/vitals'
      path: '/vitals'
      fullPath: '/vitals'
      preLoaderRoute: typeof PortalVitalsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/xray': {
      id: '/_portal/xray'
      path: '/xray'
      fullPath: '/xray'
      preLoaderRoute: typeof PortalXrayRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalPrescriptionRoute: typeof PortalPrescriptionRoute
  PortalSharingRoute: typeof PortalSharingRoute
  PortalVitalsRoute: typeof PortalVitalsRoute
  PortalXrayRoute: typeof PortalXrayRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalPrescriptionRoute: PortalPrescriptionRoute,
  PortalSharingRoute: PortalSharingRoute,
  PortalVitalsRoute: PortalVitalsRoute,
  PortalXrayRoute: PortalXrayRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PortalRoute: PortalRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
